#!/bin/sh

# Copyright (c) 2015, Adam Cammack <adam@acammack.com>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

# Usage:
#
# Minihub requires git to be in your path and .git/description to be the name
# of the repository. Curl and the environment variable GITHUB_USER=<username>
# are required to submit pull requests. It will ask for your password as
# needed.
# 
# minihub push|fetch|checkout|pull <user> <ref>
# Push, fetch, checkout, pull to/from <ref> of <user>'s repository. Note that
# checkout will put you into a detached head state, meaning you will have to
# `git checkout -b <new-branch>` or cherry-pick or pull the commits to an
# existing branch to be able to push any new commits you make.
#
# minihub pull-request|pr <user> <basebranch> <title> <message>
# Open a pull request from HEAD to <user>/<basebranch> with <title> and
# <message>. These commits must have been previously pushed to referenced
# correctly.

_minihub() {
  local git_root="$(git rev-parse --show-toplevel)/.git"
  local repo="$(cat "$git_root/description")"

  local username="$GITHUB_USER"

  case "$1" in
    push|fetch|pull) 
      git "$1" "git@github.com:$2/$repo" "$3"
      ;;
    checkout)
      _minihub fetch "$2" "$3" &&
        (git checkout FETCH_HEAD | tail -1)
      ;;
    pull-request|pr)
      # PRs can only be made from pushed commits
      cat <<JSON |
{
  "title": "$4",
  "body": "$5",
  "head": "$username:$(cat "$git_root/HEAD" | sed -e 's|ref: refs/heads/||')",
  "base": "$3"
}
JSON
        curl -u "$username" -X POST -d @- \
          "https://api.github.com/repos/$2/$repo/pulls" |
          grep '"url":' | head -1 | sed -e 's/.*"url": (.*),/\1/'
      ;;
    *)
      echo "I don't know how to '$1'"
      return 1
  esac
}

_minihub "$@"
